version: '2.39.2'
services:
  db:
    image: mysql:8.0
    container_name: nest_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nestdb
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpass
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
